import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const quotes = [
      {
        id: 1,
        userId: 158010,
        firstName: 'Russell',
        lastName: 'Dow',
        dateOfBirth: new Date('08/15/1988'),
        email: 'russell.j.dow@avanade.com',
        phone: '2063066808',
        address: '24245 183rd ave se',
        city: 'Covington',
        state: 'WA',
        zip: '98042',
        ssn: '333224444',
        price: 1298.70,
        dateQuoted: '08/31/2018',
        sold: false,
        dateSold: null,
        discarded: false,
        dateDiscarded: null,
        previousCarrier: 'Lizard',
        pastClaims: false,
        pastClaimsDiscount: null,
        movingViolations: false,
        movingViolationsDiscount: null,
        newDriver: false,
        newDriverDiscount: null,
        multiCar: false,
        multiCarDiscount: null,
        previousCarrierLizard: true,
        previousCarrierLizardDiscount: -0.05,
        previousCarrierPervasive: false,
        previousCarrierPervasiveDiscount: null,
      },
      {
        id: 2,
        userId: 158011,
        firstName: 'Roger',
        lastName: 'Dodger',
        dateOfBirth: new Date('01/15/1988'),
        email: 'rdodger@gmail.com',
        phone: '2064005898',
        address: '19218 42nd st s',
        city: 'Kent',
        state: 'WA',
        zip: '98043',
        ssn: '333114444',
        price: 1290.70,
        dateQuoted: '08/31/2018',
        sold: false,
        dateSold: null,
        discarded: true,
        dateDiscarded: new Date('08/30/2018'),
        previousCarrier: 'Lizard',
        pastClaims: false,
        pastClaimsDiscount: null,
        movingViolations: false,
        movingViolationsDiscount: null,
        newDriver: false,
        newDriverDiscount: null,
        multiCar: false,
        multiCarDiscount: null,
        previousCarrierLizard: true,
        previousCarrierLizardDiscount: -0.05,
        previousCarrierPervasive: false,
        previousCarrierPervasiveDiscount: null,
      },
      {
        id: 3,
        userId: 152011,
        firstName: 'Arthur',
        lastName: 'Chrone',
        dateOfBirth: new Date('01/12/1982'),
        email: 'achrone@gmail.com',
        phone: '2064115898',
        address: '19318 82nd st s',
        city: 'Seattle',
        state: 'WA',
        zip: '98038',
        ssn: '313224444',
        price: 1190.70,
        dateQuoted: '08/29/2018',
        sold: false,
        dateSold: null,
        discarded: false,
        dateDiscarded: null,
        previousCarrier: 'Pervasive',
        pastClaims: false,
        pastClaimsDiscount: null,
        movingViolations: false,
        movingViolationsDiscount: null,
        newDriver: false,
        newDriverDiscount: null,
        multiCar: false,
        multiCarDiscount: null,
        previousCarrierLizard: true,
        previousCarrierLizardDiscount: -0.05,
        previousCarrierPervasive: false,
        previousCarrierPervasiveDiscount: null,
      },
    ];

    return {quotes};
  }
}
